### ISSUE TITLE
Example of integration of sanction with web2py for Google OAuth2

### ISSUE THREAD

**Issue by gonvaled** [demianbrecht/sanction#2]
Would it be possible to add an example of how to integrate sanction with web2py, for Google OAuth2?

**Comment by demianbrecht** [comment]
I'm not familiar with web2py (have used Pyramid and Django myself), so I likely wouldn't be the best person to put an example together. I'd definitely welcome an example contribution from someone familiar with the framework though.

However, the example _should_ have support for all providers that have been tested with the sanction library, not only Google.

I'll leave this as an open issue for a while, but will close it as "won't fix" if nobody picks up the reins on it.

**Comment by gonvaled** [comment]
Fair enough. I am working on OAuth2 and web2py, so if I feel confident in the coming days I will try to provide the implementation. Leave if open for a couple of weeks if you can.

**Comment by demianbrecht** [comment]
Will do.

On Fri, Jul 27, 2012 at 3:03 AM, gonvaled <
reply@reply.github.com

**Comment by demianbrecht** [comment]
Closing this for now as it's been logged as an issue in web2py's bug tracker: http://code.google.com/p/web2py/issues/detail?id=933
