### ISSUE TITLE
Request token returning HTTPError: HTTP Error 400: BAD REQUEST

### ISSUE THREAD

**Issue by ghost** [demianbrecht/sanction#6]
Hi There,

I am trying to use your library on our ecommerce site. 
to test how it works I have my provider running on localhost:8000
and running my client using your library on localhost:5000

The authentication works fine but the problem is when I am asking for the request token like this: 

> ```
>     client = Client(token_endpoint="http://127.0.0.1:8000/oauth2/token/",
>         resource_endpoint="http://127.0.0.1:8000/api/email/",
>         redirect_uri="http://127.0.0.1:5000/process_login/",
>         client_id="3104a6a8cc7b905a0869308d32be2e",
>         client_secret="5433120120b8bba2a91c5cc9117ac8",
>         auth_endpoint="http://127.0.0.1:8000/oauth2/authorize/")
> ```

```
    params = {
        'code': request.GET.get('code'),
    }
```

client.request_token(params)

it gives the following stack trace:

> > > Traceback (most recent call last):
> > >   File "<console>", line 1, in <module>
> > >   File "/Users/mrahman/.virtualenvs/idp/lib/python2.7/site-packages/sanction/client.py", line 113, in request_token
> > >     'utf-8'))
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
> > >     return _opener.open(url, data, timeout)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
> > >     response = meth(req, response)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
> > >     'http', request, response, code, msg, hdrs)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 438, in error
> > >     return self._call_chain(_args)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
> > >     result = func(_args)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 521, in http_error_default
> > >     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

But if I call the request token without a dict, like this:

> response = client.request_token(code=request.GET.get('code'))

'response' is always None

Is it a bug or I am missing something. 
Any support will be really appreciated.

**Comment by demianbrecht** [comment]
Sorry for taking so long to get to this..

The first example (passing `params` in to `request_token`) will result in an error. `request_token` expects `code` as a kwarg, not in a dict passed in with `code` as a key. If you wanted to use the dict, you'd have to unpack it: `request_token(**params)`

With the second example, `request_token` doesn't return anything; it mutates the `sanction.Client` instance. Meaning, that if successful, `client.access_token` will not be `None` (as well as `refresh_token` if supported by the provider).

Hope that makes sense. Please let me know if this resolves your problems so that I can close this issue.

**Comment by demianbrecht** [comment]
I'm going to assume that this issue is now closed.
